name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Gera todo dia à meia-noite (UTC)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: BomDiaSol
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
